#!/bin/sh

message=$(cat $1)

# On recupere 0 si le commentaire de match pas avec la regexp, sinon 1 ou +
msgok=$(echo $message | grep -E "^\[((CNAM_00[0-9]{6})|(QC_[0-9]{1,3})|(ISSUE_[0-9]{1,3})|(PCC)|(MERGE)|(RG_.+)|(INSTAL)|(OUTILS)|(DOC))\]" | wc -l)
if [ $msgok -eq 0 ]
then
	echo ""
	echo "========================================================"
	echo "Mauvaise forme du message de commit"
	echo "Chaque commit doit commencer par un de ces indicateurs :"
	echo ""
	echo "[CNAM_00YYYYYY] message (YY represente un identifiant de chiffres minimum)"
	echo "[QC_YYY] message (YY represente un identifiant de chiffres minimum)"
	echo "[ISSUE_YYY] message"
	echo "[PCC] message"
	echo "[RG_*] message (* represente l'identifiant de la regle de gestion)"
	echo "[INSTAL] message"
	echo "[OUTILS] message"
	echo "[DOC] message"
	echo "[MERGE] message"
	echo ""
	echo "Veuillez retenter de commit"
	echo "========================================================"
	exit 1
fi

exit 0
